### ISSUE TITLE
Need help in beginning

### ISSUE THREAD

**Issue by yat2k** [archimodel/archimate-js#1]
How exactly do i try this out/ run this.

**Comment by vbo75** [comment]
Hi,
In order to run archimate-js lib, you need a web app. Try with archimate-js-demo.

Step 1: download archimate-js and open this project in your IDE. Install the project dependencies via `npm install`.
Step 2: download archimate-js-demo and open this project in your IDE. Edit package.json file and replace "archimate-js": "0.0.3" with your local archimate-js project path (eg. "archimate-js": "file:../archimate-js")
Step 3: install archimate-js-demo project dependencies via `npm install`.
Step 4: run the demo `npm run start`

You can now modify archimate-js files and see changes via the demo app.

**Comment by yat2k** [comment]
Thanks (sorry for the late reply :p )
