### ISSUE TITLE
Hope to get your help

### ISSUE THREAD

**Issue by zyc329** [archimodel/archimate-js#5]
I currently need to adapt to archimate version 3.2, I hope to add some nodes, or add attributes, I see a lot of archimate:xx in your code, how do I start? By the way, is the json prefix for my moddle-xml mandatory?

**Comment by vbo75** [comment]
Hi,
I use an extended XML format close to the archimate XML format with an "archimate:" prefix in front of archimate tag. Some adjustments are needed in the XML parsing engine to fully support the archimate XML format.
Will be available in a futur release.

If you want to add some other archimate attributes. You need to modify the moddle/resources/archimate.json. This file describes all tags supported by the parser. After that, you need to modify ArchimateImporter.js, ElementFactory.js and other files in order to manage businessObject with new tag.
